language: node_js
node_js: node
deploy:
  provider: heroku
  app: family-reunion-stgeorge
  api_key:
    secure: gkBrk8sENxh91bTzPBvXXuQboSSb0VlZVDPIJFmPuQNnfgw3I2qSmrfBx5M8dy2LzuicGkdkienjvmZzaIrbNgdd/7th4dASKciyCspEAcuGD2hq6ovQRNY097fE+KU9YNaCaMhxdBZuHsOqjc48Nr7jGqruKoGiqpqQea7oyTHG/s79o4J21MC2JstgEwfSu5uqrI5Tqwuvn8zrFPYUPPpc9OHcCNmUmsrXbDuMWMFT58GMzS90VD+Azycqx47wew8oSQvDzZZfj8ml/NxhmJDI05sO7QDSfOblxba2aunUW5ntaRvOPXsrl0RaEmIYE4vrdSXA8lhbXwxk3qusiVKuENa2WQQEfC6mLi6apw+xvyuLsvYakNTPINDxtUHJEbPSdPodclTuEaRogrGHTJD4gWh5ZFVeVRL69xinOHyVHL0e9BnvDz+5+HRvvEc/KBzSdzK4/HIENK24LhQhrA8bRQrxgRPKoUjgFy7/0iofNC69Imm1AiiinSfosmRM5A8QE9VZi6m/nHffcURsqGqUjGvtMtAWAy4vmLc3kfY3UlF8EGG4L46Cg3C4p2eiZox0wYT2PW5mQRDfSrihzCkeNZh4ZaYWVxlZsGIHzK410J8lsAw9Ak2A579cdpQ1nL+Ean7ZB4L6VgMMXPY0g1A24oTkci6srBbTmSsEG/k=
services: 
  - mongodb